[package]
name = "simple_email"
version = "0.1.0"
authors = ["Nelson Penn <nelsonapenn@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.30"
base64 = "0.12.3"